### ISSUE TITLE
Create documentation for adding a user / resetting their password

### ISSUE THREAD

**Issue by pcraig3** [HHS/simpler-grants-pdf-builder#48]
## Summary

Technically, everyone who is an admin user on the NOFO Builder can do this, but the written-down process needs to be created.

This will mean that if I am off, other people can do admin tasks involving creating users or helping them log in.

I have also noticed that some small improvements that can be made while creating the documentation. 

### Tasks

- [x] Write down process for creating users
- [x] Write down process for resetting user passwords
- [x] Write down the process for removing users
- [x] Reorder permissions checkboxes on user creation screen
- [x] Lowercase emails when users are created
- [x] Lowercase emails on the login screen

**Comment by pcraig3** [comment]
Merged #49 which adds some convenience/usability features for adding new users

**Comment by pcraig3** [comment]
Reassigned to Adam to review and (hopefully) close this issue.

**Comment by pcraig3** [comment]
@admoorgit, can you confirm this issue should be closed?

**Comment by pcraig3** [comment]
This is ✨ done! ✨
